name: x86-Windows-llvm-from-sources

on:
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Clone llvm-project
        run: |
          git clone --depth 1 --single-branch --branch release/13.x https://github.com/llvm/llvm-project

      - name: Build LLVM & Clang
        run: |
          cd llvm-project
          mkdir build
          cd build
          # cmake -G "Visual Studio 16 2019" -Thost=x64 `
          cmake -G Ninja `
            -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS=On `
            -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_OPTIMIZED_TABLEGEN=ON `
            -DCMAKE_BUILD_TYPE=MinSizeRel `
            ..\llvm
          # Note that only the required tools are built
          ninja clang opt lli not FileCheck

      - name: Install lit
        run: |
          pip3 install lit

      - name: Build HelloWorld
        run: |
          # Adding the location of Ninja to $PATH
          ${env:Path} += "${env:GITHUB_WORKSPACE}/llvm-project/build/bin"
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_DIR="${env:GITHUB_WORKSPACE}/llvm-project/build/lib/cmake/llvm" ../
          ninja
          lit -v test
