name: x86-Ubuntu

on:
  push:
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main"
          sudo apt-get update
          sudo apt-get install -y llvm-13 llvm-13-dev clang-13 llvm-13-tools
          sudo apt-get install python3-setuptools
          sudo pip3 install lit
      - name: Build HelloWorld
        run: |
          cd HelloWorld
          mkdir build && cd build
          cmake -DLT_LLVM_INSTALL_DIR="/usr/lib/llvm-13/" ../
          make -j2
      - name: Build llvm-tutor + run tests
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DLT_LLVM_INSTALL_DIR="/usr/lib/llvm-13/" ../
          make -j2
          lit -va test/
